name: Check PoC || GTFO Website for changes

on:
  watch:
    types: [started]
  schedule:
    - cron: "0 0 * * *"

jobs:
  checkout:
    name: Checkout repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.1
        with:
          path: pocorgtfo
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Run update.sh
        run: |
          cd pocorgtfo;
          ./update.sh